package com.knowledge.graph.backend;
import java.sql.*;
import java.util.*;


public class Questions {
	

	//The question's numeric id will be auto-generated by SQL
	public void addQuestion(String question_text, int student_id, int c_id){
		Connection connection = JdbcSqlConnection.getConnection();
		try{
			String query = "INSERT INTO AskedConceptQuestions (text, student_number, c_id)"
					+ "VALUES ("+question_text + "," + student_id + "c_id" + ");";
			Statement statement = connection.createStatement();
			statement.executeUpdate(query);
		}
		catch(SQLException e){
			System.out.println("Insertion was unsuccesful!");
			e.printStackTrace();
		}
		finally{
			if(connection!=null)
				try{
					connection.close();
				}
				catch(SQLException e){
					e.printStackTrace();
				}
		}
	}//end addQuestion
	
	public Question searchQuestionByID(int q_id){
		Connection connection = JdbcSqlConnection.getConnection();
		Question question = null;
		try{
			String query = "SELECT * FROM AskedConceptQuestions WHERE q_id="+q_id;
			Statement statement = connection.createStatement();
			ResultSet rs = statement.executeQuery(query);
			question = new Question(rs.getNString("text"),rs.getInt("q_id"), rs.getInt("student_number"), rs.getInt("c_id"));
		}
		catch(SQLException e){
			System.out.println("An error occured while searching!");
		}
		finally{
			if(connection!=null)
				try{
					connection.close();
				}
				catch(SQLException e){
					e.printStackTrace();
				}
		}	
		return question;
	}// end searchQuestionByID
	
	public List<Question> searchQuestionsBySID(int student_id){
		List<Question> q_list = new ArrayList<Question>();
		Connection connection = JdbcSqlConnection.getConnection();
		try{
			String query = "SELECT * FROM AskedConceptQuestions WHERE student_number ="+student_id;
			Statement statement = connection.createStatement();
			ResultSet rs = statement.executeQuery(query);
			
			while(rs.next()){
				Question question = new Question(rs.getNString("text"), rs.getInt("q_id"), rs.getInt("student_number"),
												rs.getInt("c_id"));
				q_list.add(question);
			}
		}
		catch(SQLException e){
			e.printStackTrace(); //Placeholder, will modify later
		}
		finally{
			if(connection!=null)
				try{
					connection.close();
				}
				catch(SQLException e){
					e.printStackTrace(); //Placeholder, will modify later
				}
		}
		return q_list;
	}//end searchQuestionsBySID
	
	public List<Answer> getTiedAnswers(int q_id){
		
		Connection connection = JdbcSqlConnection.getConnection();
		List<Answer> tied_answers = new ArrayList<Answer>();
		try{
			String query = "SELECT * FROM TiedAnswers WHERE q_id ="+q_id;
			Statement statement = connection.createStatement();
			ResultSet rs = statement.executeQuery(query);
			
			while(rs.next()){
				tied_answers.add(new Answer(rs.getNString("text"),rs.getInt("student_number"), 
						rs.getInt("q_id"),rs.getNString("status")));
			}
		}
		catch(SQLException e){
			System.out.println("An error occured while searching!");
		}
		finally{
			if(connection!=null)
				try{
					connection.close();
				}
				catch(Exception e){
					e.printStackTrace();
				}
		}
		return tied_answers;
	}//end getTiedAnswers
	
	/**
	 * 
	 * @return A list containing students who have asked at least one question in every concept
	 */
	public List<Student> getStudentEveryConcept(){
		Connection connection = JdbcSqlConnection.getConnection();
		List<Student> students = new ArrayList<Student>();
		
		try{
			Statement statement = connection.createStatement();
			//returns the number of concepts excluding "others"
			String subquery = "(SELECT COUNT(*) FROM BelongedConcepts WHERE c_id<>999999)";
			String query = "SELECT s.* FROM AskedConceptQuestions t, Students s WHERE t.student_number=s.student_number"
					      +" GROUP BY t.student_number HAVING count(DISTINCT t.c_id)="+subquery;
			ResultSet rs = statement.executeQuery(query);
			
			while(rs.next()){
				students.add(new Student(rs.getInt("student_number"), rs.getNString("first_name"),
						rs.getNString("last_name"),rs.getNString("degree"),rs.getNString("password")));
			}
		}
		catch(SQLException e){
			System.out.println("An error occured while searching!");
			e.printStackTrace();
		}
		finally{
			if(connection!=null)
				try{
					connection.close();
				}
				catch(Exception e){
					e.printStackTrace();
				}
		}
		return students;
	}//end getStudentEveryConcept
}
